/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Sun Mar 11 18:21:30 2018. */

#include "cast_channel.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t extensions_api_cast_channel_CastMessage_fields[8] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, extensions_api_cast_channel_CastMessage, protocol_version, protocol_version, 0),
    PB_FIELD(  2, STRING  , REQUIRED, CALLBACK, OTHER, extensions_api_cast_channel_CastMessage, source_id, protocol_version, 0),
    PB_FIELD(  3, STRING  , REQUIRED, CALLBACK, OTHER, extensions_api_cast_channel_CastMessage, destination_id, source_id, 0),
    PB_FIELD(  4, STRING  , REQUIRED, CALLBACK, OTHER, extensions_api_cast_channel_CastMessage, namespace_str, destination_id, 0),
    PB_FIELD(  5, UENUM   , REQUIRED, STATIC  , OTHER, extensions_api_cast_channel_CastMessage, payload_type, namespace_str, 0),
    PB_FIELD(  6, STRING  , OPTIONAL, CALLBACK, OTHER, extensions_api_cast_channel_CastMessage, payload_utf8, payload_type, 0),
    PB_FIELD(  7, BYTES   , OPTIONAL, CALLBACK, OTHER, extensions_api_cast_channel_CastMessage, payload_binary, payload_utf8, 0),
    PB_LAST_FIELD
};

const pb_field_t extensions_api_cast_channel_AuthChallenge_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t extensions_api_cast_channel_AuthResponse_fields[4] = {
    PB_FIELD(  1, BYTES   , REQUIRED, CALLBACK, FIRST, extensions_api_cast_channel_AuthResponse, signature, signature, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, CALLBACK, OTHER, extensions_api_cast_channel_AuthResponse, client_auth_certificate, signature, 0),
    PB_FIELD(  3, BYTES   , REPEATED, CALLBACK, OTHER, extensions_api_cast_channel_AuthResponse, client_ca, client_auth_certificate, 0),
    PB_LAST_FIELD
};

const pb_field_t extensions_api_cast_channel_AuthError_fields[2] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, extensions_api_cast_channel_AuthError, error_type, error_type, 0),
    PB_LAST_FIELD
};

const pb_field_t extensions_api_cast_channel_DeviceAuthMessage_fields[4] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, extensions_api_cast_channel_DeviceAuthMessage, challenge, challenge, &extensions_api_cast_channel_AuthChallenge_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, extensions_api_cast_channel_DeviceAuthMessage, response, challenge, &extensions_api_cast_channel_AuthResponse_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, extensions_api_cast_channel_DeviceAuthMessage, error, response, &extensions_api_cast_channel_AuthError_fields),
    PB_LAST_FIELD
};





/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(extensions_api_cast_channel_DeviceAuthMessage, challenge) < 65536 && pb_membersize(extensions_api_cast_channel_DeviceAuthMessage, response) < 65536 && pb_membersize(extensions_api_cast_channel_DeviceAuthMessage, error) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_extensions_api_cast_channel_CastMessage_extensions_api_cast_channel_AuthChallenge_extensions_api_cast_channel_AuthResponse_extensions_api_cast_channel_AuthError_extensions_api_cast_channel_DeviceAuthMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(extensions_api_cast_channel_DeviceAuthMessage, challenge) < 256 && pb_membersize(extensions_api_cast_channel_DeviceAuthMessage, response) < 256 && pb_membersize(extensions_api_cast_channel_DeviceAuthMessage, error) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_extensions_api_cast_channel_CastMessage_extensions_api_cast_channel_AuthChallenge_extensions_api_cast_channel_AuthResponse_extensions_api_cast_channel_AuthError_extensions_api_cast_channel_DeviceAuthMessage)
#endif


/* @@protoc_insertion_point(eof) */
